### ISSUE TITLE
Identify (potential) toolchain components

### ISSUE THREAD

**Issue by LiamMaru** [Zandwhich/Python-Table-Print#2]
Before you setup a new project in any language or environment, it pays to do some research around:

1. Continuous integration;
2. Continuous deployment;
3. Project structure;
4. Static analysis (linting, type-checking, ...);
5. dynamic analysis (testing, profiling, ...); and
6. packaging and distribution.

Off the top of my head, these are the "big 6". Ultimately what you want to do is have a great developer experience:

> If a project isn't easy, fun, and readily rewarding to work on, then nobody will want to work on it (unless you pay them loads of money).

If I can pull down your repo and run a handful of commands and do anything, that's ideal. Consider the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html): I can pull down a project and run `./gradlew test` and it should just "work". This is idea, 10/10 awesome stuff. Python is, I feel, a bit trickier, but you can still make it nice.

What I'm talking about here is the [Developer Experience](https://github.blog/2023-06-08-developer-experience-what-is-it-and-why-should-you-care/#:~:text=DevEx%20refers%20to%20the%20systems,%2C%20satisfaction%2C%20and%20operational%20impact.). Side note, don't ever call it DevEx, at least not in front of me.

---

So yeah, I think as a start, go out and research these topics and see what your options are. Post what you find under these categories and we can work our way forward from there :).

**Comment by Zandwhich** [comment]
@LiamMaru Ok, this is exactly what I want to learn with this repo; this is awesome to hear. But taking the next step, what do you reckon my approach should be?

To give context to this question: I oftentimes find myself going down rabbit holes of research, ensuring that I know everything (or very much near it) before beginning, so that my approach is "perfect". However, I have found this quite crippling.

With this project, I was thinking about just "giving it a go" and failing a lot of times. I have heard from others (read: "many ~successful~* people's Ted talks") that the best teacher is failure. With this project, I was thinking about going in (almost) blind on those above topics and just giving it a go, getting ready to fail often and learn from my mistakes.

Where do you think a fair place is to draw the line? How much research should I be doing vs actions I should be taking?

* I find 'successful' to be a subjective word and (sadly) has been co-opted a bit by the hustle culture to glorify an approach to work/life I don't quite like, hence the strikethrough.

**Comment by LiamMaru** [comment]
Yeah look, this is as much art as science. Like, nothing's perfect - personally, I'm never happy with anything, but I think it's part of the discipline to reach a point where you can ignore that voice in your head to refactor and reorganise, and just plow on with progress towards delivery. I tend to agree with the idea that "you learn the most by finishing stuff", because generally it's that journey towards silencing that voice which really pushes you beyond being more than the usual engineer. Like, engineers fall into a few categories - the best ones care about their craft (IMO). But also, the issue then is that they go overboard and aim for a perfection that's unrealistic at scale. It's a bit like trying to wage a war without casualites. Sure, you might be able to kill one guy flawlessly (Osama Bin Laden), but that aint happening at scale.

As far as your approach goes, I think the starting point should be, "don't innovate where it's not your job". Ie, it's not your job here to have an innovative toolchain. You want something that's proven, works, and provides a great experience. Like, the Toyota Camry of toolchains. With that in mind, I'd start googling things like:

* Python project layout
* Python static analysis
* Linting Python
* Packaging python

And so on. Check out the Github projects and see how popular they are. A simple metric is, older = better. More stars = better. then, cross-reference that with online discussions to make an informed choice. In general I'd say, there's nothing wrong with trying a few things, but ultimately you have to pick something and live with it. For example, I started the BMOD stuff using "setup tools" because it's proven, reliable. Ben S mentioned he prefers that to Poetry, which is fair. But ultimately, I choise poetry because setup tools is less "easy to use" than Poetry, and I figured people would like the simplicity of Poetry. This comes with some downsides (namely, people have somewhat confused it with NPM, and are treating it as such), but the fact we have no complaints about Poetry is a win. The metric, "CPM", or complaints per minute, is a good one to consider. If I'd pushed Setup tools (a much older alternative) to Poetry (newer, more modern but maybe more controversial), I reackon peple woulda hated it, and our CPM would be a lot higher.

I'm rambling, but if I were to distill it down, consider this: what are the roles involved in building/packaging/deploying your project, and if those roles were occupied by other people, what choices would you make the reduce their CPM? I feel like this is a good way to think, because it's really about empathy. Ie, how do I make people's lives suck less?

**Comment by LiamMaru** [comment]
Re. "what's enough", I think what it comes down to is:

> Will this do the job and could I reasonably justify why it failed, if it does? Are my chances of success - knowing nothing is certain - sufficient for me to proceed and if it does become apparent that I need to adjust course, am I able to change direction without unreasonable effort?

**Comment by Zandwhich** [comment]
Ok. Thanks for the input. With this in mind (when I've got the time), I'll take a look at those toolchains

**Comment by Zandwhich** [comment]
Thought about this some, and I'll go with `poetry`. Of course there's more than just that, but I'll use it to organize this project.

Pros:
* I've used it before, and I know it's fairly powerful
* It will save a lot of headache with having to manage everything separately
* I know it's (at least somewhat) used in industry; other people use it

Cons:
* My biggest fear with using `poetry` is that it'll obfuscate away a lot of learning I otherwise would've been doing...

Weighing the pros and cons, I've decided to go for it with `poetry`. This will probably bring me the most success with this project

**Comment by LiamMaru** [comment]
Good evening!

How's it all going? Sorry it took me a little while to get back to this one - hope all is well :).

I reackon, here's a suggestion... try [setuptools](https://pypi.org/project/setuptools/). I'm looking at the con, and I think the bigger con is that, you'll miss out on having a tangible feel for what the alternative to poetry is and why you'd use Poetry, and "live in blissful ignorance" :). But here's my suggestion -

> Get the project working with `setuptools`, then cut over to Poetry.

Or you could go the other way (Poetry -> Setup tools). One doesn't preclude the other, but there's nothing to say you can't try both.

**Comment by Zandwhich** [comment]
Good evening,

The last month has been hectic, but when you wrote that I was actually in secret option D: Canada.

Re: the setup tools, that sounds like a good idea and my choice with how I'll go forward for now, and then will move to Poetry.

Just a note: I'm now in NZ and will have very, very little time for this project (or any coding). So this will be a very slow burn of essentially nothing.

Keen to catch up sometime if you're free! I'd love to hear what's happening over at the old place.

**Comment by LiamMaru** [comment]
Good day!

All good dude, I figured you'd have loads on and not a lot of time to think of/stare at code :). Pretty funny you're in Canada, and that there was an option D. Could play a game of "Where in the World is Alex Z?".

Re. the above, don't sweat it. If you're keen, I've got something that might interest you. It's not a priority, it's the sort of thing you can pick up and work on as you please, and I can pay you for it. It's an IDE for my side project, it's a desktop application built on Electron in Typescript. I think it'dIf you're interested let's discuss it when you've got some time. No hurry whatsoever on this one :).

Absolutely! It'd be great to catch up. Keen to see some photos of NZ and your adventures. What's the name of the company you're working for? I'm curious :)

**Comment by Zandwhich** [comment]
Hey, I would love to catch up, but let's carry this conversation over to LinkedIn :) @LiamMaru
